### ISSUE TITLE
Message d'erreur présent dans les notifications

### ISSUE THREAD

**Issue by Cryinman82** [Jezza34000/weback#12]
Bonjour !

Je reviens vers toi pour un problème non résolu (on avait échangé par mail)

Voici ce qui s'affiche régulièrement.
Erreur sur la fonction GetThingShadowError executing "GetThingShadow" on "https://data.iot.eu-central-1.amazonaws.com/things/neatsvor-x520-48-3f-da-6c-d2-a0/shadow"; AWS HTTP error: Client error: `GET https://data.iot.eu-central-1.amazonaws.com/things/neatsvor-x520-48-3f-da-6c-d2-a0/shadow` resulted in a `403 Forbidden` response: {"message":"Forbidden","traceId":"deb52fab-7154-371f-972c-b5b300df8ed8"} ForbiddenException (client): Forbidden - {"message":"Forbidden","traceId":"deb52fab-7154-371f-972c-b5b300df8ed8"}

Je suis disponible et réactif aujourd'hui et demain.

**Comment by Jezza34000** [comment]
Hello,

Effectivement. 
J'ai aussi ce message d'erreur, et à ce jour je n'ai pas réussi à mettre la main sur le problème qui cause cette erreur.
Cela semble venir du module qui gère la partie AWS. Je vais investiguer sur les forum d'aide d'AWS...
En tout si cela peux te rassurer, j'ai posté une update (dans la version stable), et même si cette erreur vient à se produire lors de l'envoi d'un ordre au robot, un nouvel essai est effectué.

**Comment by Cryinman82** [comment]
D'accord, merci pour les précisions !

**Comment by Jezza34000** [comment]
J'ai poussé une modification sur la BETA. Je la met en test toute la journée voir si le message d'erreur disparait complètement et si c'est convainquant, je pousse demain sur la stable ;-)

**Comment by Cryinman82** [comment]
Je vais faire la mise à jour aussi ! Je te dis ce qu'il en est pour moi

**Comment by Cryinman82** [comment]
Ah pas disponible au téléchargement pour le moment en beta.

**Comment by Jezza34000** [comment]
Synchro market effectué tu dois l'avoir au téléchargement

**Comment by Jezza34000** [comment]
Bon la modification tourne depuis hier matin sur mon Jeedom, et depuis plus aucune erreur 403.
C'était simplement ma vérification du token AWS qui se faisait à la seconde près, du coup il arrivait que je sois limite entre la vérification et l'exécution de la requête.
Désormais, je prends une marge de 15 secondes.
Si tu constate que c'est rétabli de ton côté aussi, je te laisse clôturer l'issue ;-)
